### ISSUE TITLE
Unauthorized BUS

### ISSUE THREAD

**Issue by SylvainAssemat** [dschanoeh/socketcand#25]
Hi

I try to use the socketcand with java kayak test class but i m facing a problem :

client connected
**client try to acces unauthorized bus**

Does someone know what to do please ?

_candump can0 & can send working on the Rpi._

**Comment by dschanoeh** [comment]
When starting socketcand, did you make sure to add the bus you want to access to the -i option (e.g. socketcand -i can0)? Also, you might need to run socketcand as root but I'm not 100% sure.

**Comment by SylvainAssemat** [comment]
Yes all it s ok now :-)
Thanks
________________________________
